### ISSUE TITLE
Production Release Checklist

### ISSUE THREAD

**Issue by xNS5** [xNS5/rentalreviews#65]
- [x] Migrated DB changes to production environment
- [x] Merged changes in development -> main
- [x] Tested out changes in live site
- [x] Generated release notes + changelog
- [x] ???
